name: Hotbed
version: '${project.version}'
main: org.satellite.dev.progiple.hotbed.Hotbed
api-version: '1.20'
depend: [NBTAPI, LunaSpring, DecentHolograms, WorldGuard, WildLoaders]
authors: [ProGiple]
commands:
  hotbed:
    usage: /hotbed reload/give <player> <mob>
    aliases:
      - hb
      - hotb
      - hbed
permissions:
  hotbed.admin:
    default: op
  hotbed.chance.<chance>:
    default: false